blog/urls.py
from django.urls import path
from . import views 

app_name = 'blog'


urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>', views.detail, name='detail'),
]
    

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
     
    blogtitle = models.CharField(max_length=100)
    blogdate = models.DateField()  
    blogmain = models.TextField()

    def __str__(self):
        """Function to display titles into admin pages""",
        return self.blogtitle

portfolio/models.py
from django.db import models

class Project(models.Model):
     
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to = 'portfolio/image/')
    url = models.URLField(blank=True)
    
    def __str__(self):
        return self.title
        

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from portfolio.models import Project

def all_blogs(request):
    projects = Project.objects.all()
    blogs = Blog.objects.all()
    return render(request, 'blog/all_blogs.html', {'blogs': blogs,'projects': projects})

def detail(request, blog_id):
    slectedblog = get_object_or_404(Blog, pk=blog_id)
    blogs = Blog.objects.all()
    return render(request, 'blog/detail.html', {'slectedblog': slectedblog})

portfolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})
    

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html"%}
{% block content%}
<h2>Maher has written {{ projects.count }} blog{{blogs.count|pluralize}}</h2>

{% for x in blogs %}
<Div>
<a href="{% url 'blog:detail' x.id  %}"><h2>{{ x.blogtitle}}</h2></a>
<h3>{{x.blogdate|date:"M dS Y"|upper }}</h3>
<p>{{ x.blogmain|truncatechars:120 }}</p>
<!--we cab add '|safe' before truncatechars to activate html tags in mainblog from admin inpute-->
</Div>
{% endfor %}
{% endblock %}  

blog/templates/blog/detail.html
{% extends "portfolio/base.html"%}
{% block content%}
<h1>{{slectedblog.blogtitle}}</h1>
<h3>{{slectedblog.blogdate|date:"M dS Y"|upper}}</h3>
<p>{{slectedblog.blogmain}}</p>
{% endblock %}  

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Maher Portfolio</title>
  </head>
  <body>


      
    
{% block content %}{% endblock %}














    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/portfolio/home.html
{% extends "portfolio/base.html"%}
{% block content%}
  <h1>Maher Portfolio</h1>

  {% load static %}

  <a href="{% url 'blog:all_blogs' %}">Blog</a>
  <br>
  <img src="{% static 'portfolio/nnnnn.jpg' %}" height="420rem" width="480rem">
  <br>
  <a href="{% static 'portfolio/Resume.pdf' %}">Resume</a>
  

  {% for x in projects %}
  <Div>
  <img src="{{ x.image.url }}" height="220rem" width="280rem">
  <h2>{{ x.title }}</h2>

  <p>{{ x.description }}</p>
  </Div>
  {% endfor %}

{% endblock %}  